config/routes.rb
Rails.application.routes.draw do 
  devise_for :authors ,:path_names=>{sign_in: 'login',sign_out:'logout',sign_up:'register'}
  resources :products
  

  root :to =>'products#index'
end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
  PRODUCT_TYPES=["Gents","Ladies","Children"]
  validates :item_type,inclusion: PRODUCT_TYPES
  validates_uniqueness_of :name
  validates :category ,:presence=>true
  validates :description ,:presence =>true
  validates :name ,:presence => true
   validates :size ,:presence => true
   validates :image,:presence=> true
   validates :price,:numericality => {:greater_than_or_equal_to =>0.01}
 validates :image,:format => { 
    :with => %r{\.(gif|jpg|png|jpeg)$}i,:multiline =>true,
    :message => 'must be a URL for GIF ,JPG or PNG image.'
    }
  mount_uploader :image ,DesignsUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception 
  
  
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params[:author]
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_author! ,except: [:index,:show]
  # GET /products
  # GET /products.json
  def index
     @new = Product.all.order('created_at desc').limit(5)
    @products = Product.all.order('created_at desc').paginate(page: params[:page],per_page: 4) 
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :size, :featured, :image,:item_type,:category,:price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hekemje" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  
  </head>
  <body>
     <div id="banner"  class ="container" >
      <%=image_tag("logo.png")%>
      <p id="logo">HEKEMJE DESIGNS  </p>
     
      <div id="slogan">
        <p> Quality african brand!</p>
      </div>
    </div>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div id="itemcarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="active item">
          <%=image_tag("circles.jpg",:size=>"600x500",:class=>"img-responsive")%>
          <div class="container">
            <div class="carousel-caption text-centered">
             
            </div>
          </div>
        </div>
        <div class="item"><%=image_tag("noise_temp.png",:size=>"700x600",:class=>"img-responsive")%></div>
      </div>
      <a class="carousel-control left" id="carousel-navleft" href="#itemcarousel" data-slide="prev" ></a>
      <a class="carousel-control right" id="carousel-navright" href="#itemcarousel" data-slide="next"></a>
    </div>
      </div>
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Hekemje</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
           <li><%= link_to "Home", root_url %></li>
              <li><%= link_to "Gents", "/path2"  %></li>
              <li><%= link_to "Ladies", "/path3"  %></li>
               <li><%= link_to "Children", "/path3"  %></li>
               <li><%= link_to "Gallery", "/path3"  %></li>
                <li> 
                <%if author_signed_in?%>
                <%=drop_down "Account menu"  do %>
               <%=menu_item "Edit account",edit_author_registration_path%>
               <%=menu_item "Products",products_path%>
                <li><%=link_to "Logout",destroy_author_session_path,:method=>"delete"%></li>
               <%end%>
                <%else%>
                <%=link_to "Login",new_author_session_path%>
               <%end%>
                </li>
          </ul>
        </div>
      </div>
    </div>
<%= bootstrap_flash %>
    <div class="container-fluid" id="Pagemain">
          <%=yield%>
        
      <div class="row-fluid col-lg-4" id="ProductStore">
         <div class="row-fluid">
         <%=yield :new_arrivals%>
           <%=yield :about_us%>
      </div>
        
      </div>
      <div class="row-fluid col-lg-8">
          <%=yield :product_store%>
      </div>
        </div>
  
    <div class="row-fluid">
       <footer>
        <p>&copy; Company 2014</p>
         
      </footer>
    </div>
       
  </body>
   <%= javascript_include_tag "application" %>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => 'form-horizontal' } do |f| %>
<fieldset id="productreg" title="Product registration">
   <legend>Product registration</legend>
  <ol>
    <li>
        <%= f.label :name %>
       <%= f.text_field :name %>
    </li>
    <li>
        <%= f.label :description%>
       <%= f.text_field :description,:multipart=>true %>
    </li>
    <li>
      <%= f.label :size%>
       <%= f.text_field :size%>
    </li>
    <li>
      <%= f.label :price%>
       <%= f.text_field :price%>
    </li>
    <li>
       <%= f.label :category %>
       <%= f.text_field :category %>
    </li>
    <li>
      <%= f.label :item_type %>
      <%= f.select :item_type,Product::PRODUCT_TYPES,prompt:'Select product type'%>
    </li>
   
    <li>
      <%= f.label :image%>
     <%= f.file_field :image%>
    </li>
     <li class="singleline">
      <%= f.label :featured %>
       <%= f.check_box :featured %>
    </li>
    <li class="singleline">
       <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' ,:id=>'btncancel'%>
    </li>
  </ol>
</fieldset>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <p id="pagetitle"><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></p>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%content_for :product_store do%>
<div class="page-header">
  <p id="pagetitle">Product Store</p>
</div>
<table class="table container-fluid">
  
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td rowspan=<%= if author_signed_in?
  "9" else "7" end %> id="store" class="container-fluid"> <%= image_tag product.image.url().to_s,:id=>"prodListing",:class=>"img-responsive",:size=>'120x70'  if product.image? %></td>
      <tr>
        <td id="collable">Product name:</td>
          <td><%= product.name %></td>
      </tr>
      <tr>
        <td id="collable">Product description:</td>
        <td><%= product.description %></td>
      </tr>
      <tr>
        <td id="collable">Size:</td>
        <td><%= product.size %></td>
      </tr>
      <% if author_signed_in? %>
      <tr>
         <td id="collable">Feature:</td>
         <td><%= product.featured %></td>
      </tr>
      <%end%>
      <tr>
        <td id="collable">Product category:</td>
        <td><%= product.category %></td>
      </tr>
      <tr>
        <td id="collable">Item type:</td>
        <td><%= product.item_type %></td>
      </tr>
      <tr>
        <td id="collable">Price(KES):</td>
        <td> <span class="badge badge-success" id="itemPrice"><%= product.price %>/=</span></td>
      </tr>
      <% if author_signed_in? %>
      <tr>
        <td>
           <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-mini edit' %>
        </td>
        <td>
         
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
      <%end%>
      
    <% end %>
      <% if author_signed_in? %>
      <tr>
        <td colspan="3">
          <div id="newprod">
           <%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' ,:id=>"newprod" %>
          </div>
        </td>
      </tr>
      <%end%>
  </tbody>
</table>
<%if @products.count>4%>
  <div class="well">
  <ul class="pager">
      <li class="btn-mini"><%=will_paginate @products,:container=>false,remote: true,:authenticity_token => true%></li>
   </ul>
</div>
<%-end-%>
<%end%>
<%content_for :new_arrivals do%>
<div class="page-header">
  <p id="pagetitle">New arrivals</p>
</div>
   <div id="slider1_container"   style="position:  relative"  >
      
       <!-- Slides Container -->
       <div u="slides" id="slideshow">
        <% @new.each do |product| %>
       <div>   
          <%= image_tag product.image.url().to_s,:u=>"image",:class=>"img-responsive"%>
         <div u="caption" t="transition_name1" style="position: absolute; top: 30px; left: 30px; width:80%;height: 50px;font-weight: bolder">
           <span class="btn" id="Readmore"><%=link_to("View",product_path(product) ,:id=>"prodlink",:use_rails_ajax => false)%></span>
         </div>
       
       </div>
       <%end%>      
         <!-- Arrow Left -->
        <span u="arrowleft" class="jssora05l" style="width: 40px; height: 40px; top: 158px; left: 8px;">
        </span>
        <!-- Arrow Right -->
        <span u="arrowright" class="jssora05r" style="width: 40px; height: 40px; top: 158px; right: 8px">
        </span>
        <!-- Arrow Navigator Skin End -->
       
       </div>
</div>
<%end%>
<%content_for :about_us do%>   
 <p id="pagetitle">About us</p>
            <div class="well">
    <p>
       <span class="badge"> Hekemje Designs&TRADE;</span>
    </p>
    <div id="ourinfo" >
      <p>
      Hekemje designs is a place where fashion knows no age, size or gender. 
      It was founded in 2012 and is currently located in Nairobi. 
      Since 2012, it has focused on dealing with the various complexities 
      facing modern men and women. It was founded to suite all specification 
      and tastes and at the end makes you feel good and comfortable in 
      your own skin, no matter your skin or shape. It is a place where
      you can order, shop, and book whatever outfit, be it Africanized 
      clothes, African fused clothes, or even a pure westernized but unique
      designs under one roof. We also deal in accessories and handbags. 
      We also deal with fashion consultancy and deal in clothes alterations 
      to fit and get the perfect, desired look you were looking for.  
      For more information you can contact us on our facebook page:
      Hekemje African Design or our contacts below.
      </p>
       <div>
       <p>
       <span class="badge">PRODUCTS AND SERVICES</span>
    </p>
     <p>
       <span class="badge">SERVICES</span>
    </p>
    <ol>
        <li>Cloth alterations </li>
        <li>Custom made designs (Vitenges/Western)</li>
        <li>Fashion Consultancy and Buying Tips</li>
        <li>African Fabrics (Vitenges and Kangas)</li>
      </ol>
     <p>
       <span class="badge">PRODUCTS</span>
    </p>
    <ol>
      <li>Custom made designs </li>
      <li>Accessories and Handbags</li>
      <li>Fabrics of Purely African descent</li>
    </ol>
    </div>
    </div>
    </div>     
<%end%>


 

app/views/products/new.html.erb
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<div class="ProductStore">
  <%- model_class = Product -%>
<div class="page-header">
  <p id="pagetitle"><%=t '.title', :default =>  @product.name  %></p>
</div>
<dl class="dl-horizontal">
  <table class="table container-fluid">
    <tbody>
      <tr>
        
        <td rowspan=<%= if author_signed_in?
  "8" else "6" end %>  class="container-fluid"> <%= image_tag @product.image.url().to_s,:id=>"prodListing" if @product.image? %></td>
      <tr>
      <tr>
        <td><strong><%= model_class.human_attribute_name(:description) %>:</strong></td>
       
        <td><%= @product.description %></td>
      </tr>
      <tr>
        <td>
          <strong><%= model_class.human_attribute_name(:category) %>:</strong>
        </td>
        
        <td>
          <%= @product.category %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>
            <%= model_class.human_attribute_name(:item_type) %>:
          </strong>
        </td>
       
        <td>
            <%= @product.item_type %>
        </td>
      </tr>
      <%if author_signed_in? %>
      <tr>
        <td>
          <strong><%= model_class.human_attribute_name(:featured) %>:</strong>
        </td>
        
        <td>
          <%= @product.featured %>
        </td>
      </tr>
      <%end%>
      <tr>
        <td>
          <strong><%= model_class.human_attribute_name(:price) %> KES:</strong>
        </td>
       
        <td>
          <span class="badge badge-success" id="itemPrice"> <%= @product.price %>/=</span>
        </td>
      </tr>
      <% if  author_signed_in?%>
      <tr>
       <td>
           <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn' %>
        </td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
        </td>
       
      </tr>
      <%end%>
    </tbody>
  </table>
</dl>

</div>